version: '3'

services:
  
  frontend:
    image: ghcr.io/jbonifay/uberclone-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  backend:
    image: ghcr.io/jbonifay/uberclone-backend:latest
    expose:
      - "9001:8080"