version: '3'

services:
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  
  frontend:
    image: ghcr.io/jbonifay/uberclone-frontend:latest
    volumes:
      - /root/certs:/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - uberclone
  
  backend:
    image: ghcr.io/jbonifay/uberclone-backend:latest
    ports:
      - "8080:8080"
    networks:
      - uberclone

networks:
  uberclone: