version: '3'

services:
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  
  frontend:
    image: ghcr.io/jbonifay/bolber-frontend:latest
    volumes:
      - /root/certs:/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
  
  backend:
    image: ghcr.io/jbonifay/bolber-backend:latest
    expose:
      - 8080
    networks:
      - frontend

networks:
  frontend: